checker/urls.py
# from django.urls import path
# from django.conf.urls import url

from . import views
from django.urls import path

app_name = 'checker'
urlpatterns = [
    path(r'', views.IndexAll.as_view(), name='index'),
    path(r'item/<int:item_id>/', views.ArticleView.as_view(), name='detail'),
    path(r'item/<int:pk>/update/', views.ArticleUpdate.as_view(), name='update_article'),
    path(r'item/create/', views.ArticleCreate.as_view(), name='create_article'),
    path(r'item/<int:pk>/delete/', views.ArticleDelete.as_view(), name='delete_article'),
]

viewer/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('checker.urls', namespace='checker')),
    path('admin/', admin.site.urls),
]

checker/models.py
from __future__ import unicode_literals

from django.db import models
import django.utils.timezone as tz


class BotItem(models.Model):
    item_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255, blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    url = models.CharField(max_length=2000)
    original_date = models.DateTimeField(default=tz.now)
    author = models.CharField(max_length=255, blank=True, null=True)
    source_id = models.IntegerField(blank=True, null=True)
    item_id_in_source = models.CharField(max_length=2000)
    author_id = models.CharField(max_length=255, blank=True, null=True)
    # add created_by field for source table

    def __str__(self):
        return self.title

    class Meta:
        # managed = False
        db_table = 'bot_items\".\"items'

checker/forms.py
from .models import BotItem
# from django import forms
from django.forms import ModelForm


class UpdateForm(ModelForm):
    # Left if confirm needed
    # def save(self, commit=True):
    #     instance = super(UpdateForm, self).save(commit=False)
    #     if commit:
    #         instance.save(update_fields=['title', 'body', 'original_date', 'author', 'author_id'])
    #     return instance

    class Meta:
        model = BotItem
        fields = ['title', 'body', 'url', 'original_date', 'author', 'author_id']

checker/views.py
from django.views import generic
from django.views.generic.edit import UpdateView
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from .models import BotItem
from django.shortcuts import reverse
from .forms import UpdateForm


class ArticleView(DetailView):
    queryset = BotItem.objects.filter()
    model = BotItem
    ordering = ['-original_date']
    template_name = 'detail.html'
    pk_url_kwarg = 'item_id'


class IndexAll(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'latest_item_list'
    model = BotItem
    paginate_by = 10
    queryset = BotItem.objects.order_by('-original_date')


class ArticleUpdate(UpdateView):
    model = BotItem
    template_name = 'update_article.html'
    form_class = UpdateForm
    # pk_url_kwarg = 'item_id'

    def get_context_data(self, **kwargs):
        context = super(UpdateView, self).get_context_data(**kwargs)
        return context

    def get_success_url(self, **kwargs):
        return reverse("checker:detail", kwargs={'item_id': self.object.item_id})


class ArticleCreate(CreateView):

    model = BotItem
    template_name = 'update_article.html'
    form_class = UpdateForm

    def get_success_url(self, **kwargs):
        return reverse("checker:index")


class ArticleDelete(DeleteView):
    model = BotItem
    template_name = 'confirm_delete.html'

    def get_success_url(self, **kwargs):
        return reverse("checker:index")

checker/templates/base.html
<html lang="{{ LANGUAGE_CODE|default:'en' }}">
  <head>
    <title>{% block title %}Viewer UI{% endblock title %}</title>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="">
  </head>

  <body>
    <div id="wrapper">
      <style media="screen">
      p.head-logo {
            font-size: 200%;
            font-weight: bold;
            }
            /* #page-content{
              width: 100%;
              height: 100%;
            } */
      </style>
      <p class="head-logo">Viewer UI</p>

      <div id="page-content-wrapper">
        <hr class="no-margin" />
        <div class="container-fluid" id="page-content">
          <div class="row">
            <div class="col-lg-12">
              {% block content %}
              {% endblock content %}
              {% block pagination %}
                {% include 'pagination.html' %}
              {% endblock pagination %}
            </div>
          </div>
        </div>
      </div><!-- /#page-content-wrapper -->
  </div><!-- /#wrapper -->
  <footer>
    <hr class="no-margin" />
    <!-- logo here -->
  </footer>
  </body>
</html>

checker/templates/confirm_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
    <a href="{{ view.get_success_url }}" class="btn btn-default">Cancel</a>
</form>
{% endblock content %}

checker/templates/detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ object.title }}</h1>
<p>{{ object.body }}</p>
<a href={{ object.url }} target="_blank">Link to content site</a>
<br>
<a href="{%url 'checker:update_article' pk=object.item_id%}">Edit</a>
<a href="{%url 'checker:delete_article' pk=object.item_id%}">Delete</a>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% endblock content %}

checker/templates/index.html
{% extends "base.html" %}
{% block content %}
  {% if latest_item_list %}
  <ul>
  {% for item in latest_item_list %}
  <li><a href="{%url 'checker:detail' item_id=item.item_id%}">{{ item.title }}</a></li>
      {% endfor %}
  </ul>
  {% else %}
  <p>
  <strong>No items available</strong>
  </p>
  {% endif %}
  <a href="{%url 'checker:create_article'%}">Create</a>

{% endblock content %}

checker/templates/pagination.html
<style>
#pagination-menu ul{
  list-style: none;
}
#pagination-menu li{
  display: inline;
}
{% if is_paginated %}
</style>
<div id="pagination-menu">
      <ul class="pagination">
{% if page_obj.has_previous %}
     <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
{% else %}
     <li class="disabled"><span>&laquo;</span></li>
{% endif %}
{% for i in paginator.page_range %}
{% if page_obj.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
{% else %}
    <li><a href="?page={{ i }}">{{ i }}</a></li>
{% endif %}
{% endfor %}
{% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
{% else %}
    <li class="disabled"><span>&raquo;</span></li>
{% endif %}
 </ul>
</div>
{% endif %}
<a id="back-to-top" href="#" class="btn btn-lg back-to-top" role="button" data-toggle="tooltip" data-placement="left">
  <span class="glyphicon glyphicon-chevron-up"></span>
</a>

checker/templates/update_article.html
{% extends "base.html" %}
{% block content %}
<style>
#tabmenu {
  list-style: none;
}
</style>
<form action="{{ action }}" method="POST">
  {% csrf_token %}
  <!-- <span id="form-list"> -->
  <ul id="tabmenu">
    {% for field in form %}
      <div>{{ field.name }}</div>
      <li class="tab">{{ field }}</li>
    {% endfor %}
  </ul>
  <!-- </span> -->
  <input type="submit" value="Save" />
</form>
{% endblock content %}